// ── Import Center configuration — field maps, labels, templates ──────────────

export const ENTITY_KNOWN_FIELDS = {
  Contact: ["full_name", "company", "email", "phone", "notes", "type", "status", "address", "city", "country", "tax_id", "website",
    "fiscal_legal_name", "fiscal_address", "fiscal_city", "fiscal_country", "fiscal_zip", "fiscal_currency", "fiscal_payment_terms",
    "fiscal_bank_name", "fiscal_iban", "fiscal_swift",
    "ContactName", "EmailAddress", "PhoneNumber", "MobileNumber", "AccountNumber", "Website", "LegalName", "TaxNumber",
    "BankAccountName", "BankAccountNumber", "BankAccountParticulars",
    "PostalAddressLine1", "PostalCity", "PostalCountry", "StreetAddressLine1", "StreetCity", "StreetCountry",
    "CompanyName", "FirstName", "LastName"],
  ChartOfAccount: ["Code", "Name", "Type", "Tax Code", "Description", "Dashboard", "Enable Payments", "Balance", "code", "name", "type", "description"],
  Invoice: ["contact_name", "issue_date", "due_date", "total", "status", "notes", "number", "reference", "currency", "subtotal", "tax_amount",
    "ContactName", "EmailAddress", "InvoiceNumber", "InvoiceDate", "DueDate", "Total", "TaxTotal", "AccountCode", "Description",
    "Quantity", "UnitAmount", "Discount", "TaxAmount", "TaxType", "Currency", "Status", "Reference"],
  Bill: ["contact_name", "issue_date", "due_date", "total", "status", "notes", "number", "reference", "currency", "subtotal", "tax_amount",
    "ContactName", "EmailAddress", "InvoiceNumber", "InvoiceDate", "DueDate", "Total", "TaxTotal", "AccountCode", "Description",
    "Quantity", "UnitAmount", "Discount", "TaxAmount", "TaxType", "Currency", "Status", "Reference"],
  Project: ["name", "reference", "type", "status", "contact_name", "contact_phone", "contact_email", "contact_person", "start_date", "end_date", "budget", "currency", "location", "location_name", "maps_link", "location_lat", "location_lng", "description", "notes", "tags",
    "ProjectName", "ProjectCode", "ClientName", "ContactName", "StartDate", "EndDate", "Budget", "Location", "LocationName", "MapsLink", "Latitude", "Longitude", "ContactPhone", "ContactEmail", "ContactPerson"],
  WorkOrder: ["title", "reference", "status", "priority", "type", "project_name", "contact_name", "asset_name", "scheduled_date", "due_date", "location", "description", "notes",
    "Title", "WorkOrderTitle", "ProjectName", "ContactName", "ClientName", "AssetName", "ScheduledDate", "DueDate"],
  Task: ["title", "reference", "description", "status", "category", "work_order_name", "project_name", "contact_name", "asset_name", "planning_date", "planning_time_in", "planning_time_out", "priority", "notes", "location_address",
    "Title", "Name", "TaskName", "Reference", "Code", "Description", "Status", "Category", "Type", "Priority",
    "WorkOrder", "WorkOrderName", "Project", "ProjectName", "ClientName", "ContactName", "Company", "Customer",
    "AssetName", "Asset", "PlannedDate", "ScheduledDate", "Date", "StartTime", "EndTime", "Notes", "Location", "Address"],
  TimeEntry: ["employee_name", "task_title", "work_order_name", "project_name", "contact_name", "asset_name", "clock_in_time", "clock_out_time", "duration_minutes", "status", "notes", "clock_in_address", "clock_out_address",
    "Employee", "EmployeeName", "Worker", "Staff", "Task", "TaskTitle", "TaskName", "WorkOrder", "WorkOrderName",
    "Project", "ProjectName", "Client", "ClientName", "Company", "ContactName", "Asset", "AssetName",
    "ClockIn", "ClockOut", "CheckIn", "CheckOut", "ClockInTime", "ClockOutTime", "StartTime", "EndTime", "Date",
    "Duration", "DurationMinutes", "Hours", "Notes", "ClockInAddress", "ClockOutAddress", "Location"],
  Employee: ["full_name", "email", "phone", "role", "department", "status", "hire_date", "notes",
    "FullName", "Name", "Email", "Phone", "Role", "Department", "Status", "HireDate", "Notes"],
  Asset: ["name", "serial_number", "reference", "category", "status", "manufacturer", "model", "year",
    "purchase_date", "purchase_price", "currency", "location", "notes",
    "Name", "SerialNumber", "Reference", "Category", "Status", "Manufacturer", "Model", "Year",
    "PurchaseDate", "PurchasePrice", "Currency", "Location", "Notes"],
  BankAccount: ["name", "bank_name", "account_number", "account_type", "currency", "chart_account_code", "chart_account_name", "opening_balance", "opening_balance_date", "status", "show_on_dashboard", "enable_payments", "color",
    "AccountName", "Name", "AccountNumber", "BankAccountNumber", "AccountType", "Type", "Currency", "CurrencyCode", "Balance", "BankAccountName", "BankName", "Code", "AccountCode", "Status", "Dashboard", "Enable Payments"],
  BankTransaction: ["bank_account_name", "date", "description", "reference", "type", "amount", "currency", "contact_name", "contact_id", "account_code", "account_name", "status", "source_type", "source_number", "notes",
    "Date", "Amount", "Payee", "Description", "Particulars", "Code", "Reference", "TransactionType", "Transaction Type", "Reconciled", "Currency", "BankAccountName", "BankAccount"],
};

export const ENTITY_APP_FIELDS = {
  Contact: ["reference", "full_name", "company", "email", "phone", "type", "status", "address", "city", "country", "tax_id", "website", "notes",
    "fiscal_legal_name", "fiscal_address", "fiscal_city", "fiscal_country", "fiscal_zip", "fiscal_currency", "fiscal_payment_terms",
    "fiscal_bank_name", "fiscal_iban", "fiscal_swift",
    "_cp_first_name", "_cp_last_name", "_cp_email", "_cp_phone", "_cp_role"],
  ChartOfAccount: ["code", "name", "type", "subtype", "description", "tax_rate_name", "show_on_dashboard", "enable_payments", "opening_balance"],
  Invoice: ["number", "reference", "contact_name", "email_address", "issue_date", "due_date", "currency", "subtotal", "tax_amount", "total", "status", "notes",
    "_li_description", "_li_account_code", "_li_quantity", "_li_unit_price", "_li_discount", "_li_tax_rate", "_li_tax_amount", "_li_total"],
  Bill: ["number", "reference", "contact_name", "email_address", "issue_date", "due_date", "currency", "subtotal", "tax_amount", "total", "status", "notes",
    "_li_description", "_li_account_code", "_li_quantity", "_li_unit_price", "_li_discount", "_li_tax_rate", "_li_tax_amount", "_li_total"],
  Project: ["name", "reference", "type", "status", "contact_name", "contact_phone", "contact_email", "contact_person", "start_date", "end_date", "budget", "currency", "location", "location_name", "maps_link", "location_lat", "location_lng", "description", "notes", "tags"],
  WorkOrder: ["title", "reference", "status", "priority", "type", "project_name", "contact_name", "asset_name", "scheduled_date", "due_date", "location", "description", "notes"],
  Task: ["title", "reference", "description", "status", "category", "work_order_name", "project_name", "contact_name", "asset_name", "planning_date", "planning_time_in", "planning_time_out", "priority", "notes", "location_address", "location_lat", "location_lng", "allowed_radius_m"],
  TimeEntry: ["employee_name", "task_title", "work_order_name", "project_name", "contact_name", "asset_name", "clock_in_time", "clock_out_time", "duration_minutes", "status", "notes", "clock_in_address", "clock_out_address", "clock_in_lat", "clock_in_lng", "clock_out_lat", "clock_out_lng", "on_site"],
  Employee: ["full_name", "email", "phone", "role", "department", "status", "hire_date", "notes"],
  Asset: ["name", "serial_number", "reference", "category", "status", "manufacturer", "model", "year",
    "purchase_date", "purchase_price", "currency", "location", "notes"],
  BankAccount: ["name", "bank_name", "account_number", "account_type", "currency", "chart_account_code", "opening_balance", "opening_balance_date", "status", "show_on_dashboard", "enable_payments", "color"],
  BankTransaction: ["bank_account_name", "date", "description", "reference", "type", "amount", "currency", "contact_name", "account_code", "status", "source_type", "source_number", "notes"],
};

export const ENTITY_REQUIRED_FIELDS = {
  Contact: ["full_name"],
  ChartOfAccount: ["name"],
  Invoice: ["contact_name"],
  Bill: ["contact_name"],
  Project: ["name"],
  WorkOrder: ["title"],
  Task: ["title"],
  TimeEntry: ["employee_name", "task_title", "clock_in_time"],
  Employee: ["full_name", "email"],
  Asset: ["name"],
  BankAccount: ["name"],
  BankTransaction: ["date", "amount"],
};

export const FIELD_LABELS = {
  Contact: {
    reference: "Reference / Account Number",
    full_name: "Company Name",
    company: "Short Name / Nickname",
    email: "Email",
    phone: "Phone",
    type: "Category (Customer/Supplier)",
    status: "Status",
    address: "Street Address",
    city: "City",
    country: "Country",
    tax_id: "Tax ID / VAT Number",
    website: "Website",
    notes: "Notes",
    fiscal_legal_name: "Legal / Fiscal Name",
    fiscal_address: "Fiscal Address",
    fiscal_city: "Fiscal City",
    fiscal_country: "Fiscal Country",
    fiscal_zip: "Fiscal ZIP / Postal Code",
    fiscal_currency: "Currency",
    fiscal_payment_terms: "Payment Terms",
    fiscal_bank_name: "Bank Name",
    fiscal_iban: "IBAN / Account Number",
    fiscal_swift: "SWIFT / BIC",
    _cp_first_name: "Contact Person — First Name",
    _cp_last_name: "Contact Person — Last Name",
    _cp_email: "Contact Person — Email",
    _cp_phone: "Contact Person — Phone",
    _cp_role: "Contact Person — Role / Title",
  },
  Invoice: {
    number: "Invoice Number",
    reference: "Reference",
    contact_name: "Contact Name",
    email_address: "Email Address",
    issue_date: "Issue Date",
    due_date: "Due Date",
    currency: "Currency",
    subtotal: "Subtotal",
    tax_amount: "Tax Total",
    total: "Total",
    status: "Status",
    notes: "Notes",
    _li_description: "Line Item — Description",
    _li_account_code: "Line Item — Account Code",
    _li_quantity: "Line Item — Quantity",
    _li_unit_price: "Line Item — Unit Price",
    _li_discount: "Line Item — Discount %",
    _li_tax_rate: "Line Item — Tax Type",
    _li_tax_amount: "Line Item — Tax Amount",
    _li_total: "Line Item — Line Total",
  },
  Bill: {
    number: "Bill Number",
    reference: "Reference",
    contact_name: "Contact Name",
    email_address: "Email Address",
    issue_date: "Issue Date",
    due_date: "Due Date",
    currency: "Currency",
    subtotal: "Subtotal",
    tax_amount: "Tax Total",
    total: "Total",
    status: "Status",
    notes: "Notes",
    _li_description: "Line Item — Description",
    _li_account_code: "Line Item — Account Code",
    _li_quantity: "Line Item — Quantity",
    _li_unit_price: "Line Item — Unit Price",
    _li_discount: "Line Item — Discount %",
    _li_tax_rate: "Line Item — Tax Type",
    _li_tax_amount: "Line Item — Tax Amount",
    _li_total: "Line Item — Line Total",
  },
  Project: {
    name: "Project Name",
    reference: "Project Reference / Code",
    type: "Project Type",
    status: "Status",
    contact_name: "Client / Contact Name",
    contact_phone: "Client Phone",
    contact_email: "Client Email",
    contact_person: "Client Contact Person",
    start_date: "Start Date",
    end_date: "End Date",
    budget: "Budget Amount",
    currency: "Currency",
    location: "Location / Site Address",
    location_name: "Location Display Name",
    maps_link: "Google Maps URL",
    location_lat: "Latitude",
    location_lng: "Longitude",
    description: "Description",
    notes: "Internal Notes",
    tags: "Tags (comma-separated)",
  },
  WorkOrder: {
    title: "Work Order Title",
    reference: "Reference / Code",
    status: "Status",
    priority: "Priority",
    type: "Type",
    project_name: "Linked Project Name",
    contact_name: "Client / Contact Name",
    asset_name: "Asset Name",
    scheduled_date: "Scheduled Date",
    due_date: "Due Date",
    location: "Location",
    description: "Description",
    notes: "Internal Notes",
  },
  Task: {
    title: "Task Title",
    status: "Status",
    category: "Category",
    work_order_name: "Linked Work Order",
    project_name: "Linked Project",
    contact_name: "Client / Contact",
    planning_date: "Planned Date",
    planning_time_in: "Start Time",
    planning_time_out: "End Time",
    priority: "Priority",
    notes: "Notes",
    location_address: "Location Address",
  },
  TimeEntry: {
    employee_name: "Employee Name",
    task_title: "Task Title",
    work_order_name: "Work Order Name",
    project_name: "Project Name",
    contact_name: "Client / Contact Name",
    asset_name: "Asset Name",
    clock_in_time: "Clock In Time",
    clock_out_time: "Clock Out Time",
    duration_minutes: "Duration (minutes)",
    status: "Status",
    notes: "Notes",
    clock_in_address: "Clock In Address",
    clock_out_address: "Clock Out Address",
    clock_in_lat: "Clock In Latitude",
    clock_in_lng: "Clock In Longitude",
    clock_out_lat: "Clock Out Latitude",
    clock_out_lng: "Clock Out Longitude",
    on_site: "On Site",
  },
  Employee: {
    full_name: "Full Name",
    email: "Email",
    phone: "Phone",
    role: "Role",
    department: "Department",
    status: "Status",
    hire_date: "Hire Date",
    notes: "Notes",
  },
  Asset: {
    name: "Asset Name",
    serial_number: "Serial Number",
    reference: "Internal Reference",
    category: "Category",
    status: "Status",
    manufacturer: "Manufacturer",
    model: "Model",
    year: "Year",
    purchase_date: "Purchase Date",
    purchase_price: "Purchase Price",
    currency: "Currency",
    location: "Location",
    notes: "Notes",
  },
  BankAccount: {
    name: "Account Name",
    bank_name: "Bank / Institution Name",
    account_number: "Account Number",
    account_type: "Account Type",
    currency: "Currency",
    chart_account_code: "Chart of Account Code",
    opening_balance: "Opening Balance",
    opening_balance_date: "Opening Balance Date",
    status: "Status",
    show_on_dashboard: "Show on Dashboard",
    enable_payments: "Enable Payments",
    color: "Color",
  },
  BankTransaction: {
    bank_account_name: "Bank Account Name",
    date: "Date",
    description: "Description",
    reference: "Reference",
    type: "Transaction Type",
    amount: "Amount",
    currency: "Currency",
    contact_name: "Payee / Contact",
    account_code: "Account Code",
    status: "Reconciled Status",
    source_type: "Source Type",
    source_number: "Source Number",
    notes: "Notes",
  },
};

export const XERO_CONTACT_FIELD_MAP = {
  "ContactName": "full_name",
  "CompanyName": "company",
  "EmailAddress": "email",
  "PhoneNumber": "phone",
  "MobileNumber": "phone",
  "AccountNumber": "reference",
  "Website": "website",
  "LegalName": "fiscal_legal_name",
  "TaxNumber": "tax_id",
  "BankAccountName": "fiscal_bank_name",
  "BankAccountNumber": "fiscal_iban",
  "BankAccountParticulars": "notes",
  "PostalAddressLine1": "address",
  "PostalCity": "city",
  "PostalCountry": "country",
  "StreetAddressLine1": "address",
  "StreetCity": "city",
  "StreetCountry": "country",
  "FirstName": "_cp_first_name",
  "LastName": "_cp_last_name",
  "Skype": null,
  "Twitter": null,
  "Facebook": null,
};

export const XERO_COA_FIELD_MAP = {
  "Code": "code",
  "Name": "name",
  "Type": "type",
  "Description": "description",
  "Tax Code": "tax_rate_name",
  "Dashboard": "show_on_dashboard",
  "Expense Claims": null,
  "Enable Payments": "enable_payments",
  "Balance": "opening_balance",
};

export const XERO_INVOICE_FIELD_MAP = {
  "InvoiceNumber": "number",
  "Reference": "reference",
  "ContactName": "contact_name",
  "EmailAddress": "email_address",
  "InvoiceDate": "issue_date",
  "DueDate": "due_date",
  "PlannedDate": null,
  "Total": "total",
  "TaxTotal": "tax_amount",
  "InvoiceAmountPaid": "amount_paid",
  "InvoiceAmountDue": null,
  "Currency": "currency",
  "Type": null,
  "Status": "status",
  "Sent": null,
  "InventoryItemCode": "_li_account_code",
  "Description": "_li_description",
  "Quantity": "_li_quantity",
  "UnitAmount": "_li_unit_price",
  "Discount": "_li_discount",
  "LineAmount": "_li_total",
  "TaxAmount": "_li_tax_amount",
  "TaxType": "_li_tax_rate",
  "AccountCode": "_li_account_code",
  "POAddressLine1": null, "POAddressLine2": null, "POAddressLine3": null, "POAddressLine4": null,
  "POCity": null, "PORegion": null, "POPostalCode": null, "POCountry": null,
  "SAAddressLine1": null, "SAAddressLine2": null, "SAAddressLine3": null, "SAAddressLine4": null,
  "SACity": null, "SARegion": null, "SAPostalCode": null, "SACountry": null,
  "TrackingName1": null, "TrackingOption1": null, "TrackingName2": null, "TrackingOption2": null,
};

export const COMMON_PROJECT_FIELD_MAP = {
  "ProjectName": "name", "Name": "name",
  "ProjectCode": "reference", "Code": "reference", "Reference": "reference",
  "Type": "type", "Status": "status",
  "ClientName": "contact_name", "ContactName": "contact_name", "Customer": "contact_name",
  "ContactPhone": "contact_phone", "ClientPhone": "contact_phone", "Phone": "contact_phone",
  "ContactEmail": "contact_email", "ClientEmail": "contact_email", "Email": "contact_email",
  "ContactPerson": "contact_person", "ClientContact": "contact_person", "ProjectManager": "contact_person",
  "StartDate": "start_date", "EndDate": "end_date",
  "Budget": "budget", "Currency": "currency",
  "Location": "location", "Site": "location", "Address": "location",
  "LocationName": "location_name", "SiteName": "location_name",
  "MapsLink": "maps_link", "GoogleMaps": "maps_link",
  "Latitude": "location_lat", "Longitude": "location_lng",
  "Description": "description", "Notes": "notes", "Tags": "tags",
};

export const COMMON_WORKORDER_FIELD_MAP = {
  "Title": "title", "WorkOrderTitle": "title", "Name": "title",
  "Reference": "reference", "Code": "reference",
  "Status": "status", "Priority": "priority", "Type": "type", "Category": "type",
  "ProjectName": "project_name", "Project": "project_name",
  "ContactName": "contact_name", "ClientName": "contact_name", "Customer": "contact_name", "Company": "contact_name",
  "AssetName": "asset_name", "Asset": "asset_name",
  "AssignedTo": "assigned_to", "Assigned To": "assigned_to", "Assignee": "assigned_to",
  "ScheduledDate": "scheduled_date", "DueDate": "due_date",
  "Location": "location", "Description": "description", "Notes": "notes",
};

export const COMMON_TASK_FIELD_MAP = {
  "Title": "title", "Name": "title", "TaskName": "title", "Task": "title",
  "Reference": "reference", "Code": "reference", "TaskCode": "reference",
  "Description": "description", "Details": "description",
  "Status": "status",
  "Category": "category", "Type": "category",
  "Priority": "priority",
  "WorkOrder": "work_order_name", "WorkOrderName": "work_order_name", "WO": "work_order_name",
  "Project": "project_name", "ProjectName": "project_name",
  "ClientName": "contact_name", "ContactName": "contact_name", "Company": "contact_name", "Customer": "contact_name", "Client": "contact_name",
  "AssetName": "asset_name", "Asset": "asset_name", "Equipment": "asset_name",
  "PlannedDate": "planning_date", "ScheduledDate": "planning_date", "Date": "planning_date", "PlanningDate": "planning_date",
  "StartTime": "planning_time_in", "TimeIn": "planning_time_in", "PlanningTimeIn": "planning_time_in",
  "EndTime": "planning_time_out", "TimeOut": "planning_time_out", "PlanningTimeOut": "planning_time_out",
  "Notes": "notes", "Note": "notes",
  "Location": "location_address", "Address": "location_address", "Site": "location_address",
};

export const COMMON_TIMEENTRY_FIELD_MAP = {
  "Employee": "employee_name", "EmployeeName": "employee_name", "Worker": "employee_name", "Staff": "employee_name",
  "Task": "task_title", "TaskTitle": "task_title", "TaskName": "task_title",
  "WorkOrder": "work_order_name", "WorkOrderName": "work_order_name", "WO": "work_order_name",
  "Project": "project_name", "ProjectName": "project_name",
  "ClientName": "contact_name", "ContactName": "contact_name", "Company": "contact_name", "Customer": "contact_name", "Client": "contact_name",
  "AssetName": "asset_name", "Asset": "asset_name", "Equipment": "asset_name",
  "ClockIn": "clock_in_time", "ClockInTime": "clock_in_time", "CheckIn": "clock_in_time", "StartTime": "clock_in_time", "Date": "clock_in_time",
  "ClockOut": "clock_out_time", "ClockOutTime": "clock_out_time", "CheckOut": "clock_out_time", "EndTime": "clock_out_time",
  "Duration": "duration_minutes", "DurationMinutes": "duration_minutes", "Hours": "duration_minutes",
  "Notes": "notes", "Note": "notes",
  "ClockInAddress": "clock_in_address", "ClockOutAddress": "clock_out_address",
  "Location": "clock_in_address", "Address": "clock_in_address",
};

export const COMMON_ASSET_FIELD_MAP = {
  "Name": "name", "AssetName": "name",
  "SerialNumber": "serial_number", "Serial": "serial_number", "ChassisNumber": "serial_number",
  "Reference": "reference", "Code": "reference", "AssetCode": "reference",
  "Category": "category", "Type": "category",
  "Status": "status",
  "Manufacturer": "manufacturer", "Brand": "manufacturer",
  "Model": "model", "ModelNumber": "model",
  "Year": "year", "YearOfManufacture": "year",
  "PurchaseDate": "purchase_date", "DateOfPurchase": "purchase_date",
  "PurchasePrice": "purchase_price", "Cost": "purchase_price", "Price": "purchase_price",
  "Currency": "currency",
  "Location": "location", "Site": "location",
  "Notes": "notes",
};

export const COMMON_EMPLOYEE_FIELD_MAP = {
  "FullName": "full_name", "Name": "full_name", "EmployeeName": "full_name",
  "Email": "email", "EmailAddress": "email",
  "Phone": "phone", "PhoneNumber": "phone", "Mobile": "phone",
  "Role": "role", "JobTitle": "role", "Position": "role",
  "Department": "department",
  "Status": "status",
  "HireDate": "hire_date", "StartDate": "hire_date", "JoinDate": "hire_date",
  "Notes": "notes",
};

export const XERO_BANK_ACCOUNT_FIELD_MAP = {
  "AccountName": "name", "Name": "name",
  "AccountNumber": "account_number", "BankAccountNumber": "account_number",
  "AccountType": "account_type", "Type": "account_type",
  "Currency": "currency", "CurrencyCode": "currency",
  "Balance": "opening_balance",
  "BankAccountName": "bank_name", "BankName": "bank_name",
  "Code": "chart_account_code", "AccountCode": "chart_account_code",
  "Status": "status",
  "Dashboard": "show_on_dashboard",
  "Enable Payments": "enable_payments",
  "Description": null,
};

export const XERO_BANK_TRANSACTION_FIELD_MAP = {
  "Date": "date",
  "Amount": "amount",
  "Payee": "contact_name",
  "Description": "description",
  "Particulars": "reference",
  "Code": "account_code",
  "Reference": "reference",
  "TransactionType": "type", "Transaction Type": "type",
  "Reconciled": "status",
  "Currency": "currency",
  "BankAccountName": "bank_account_name", "BankAccount": "bank_account_name",
  "Source": "source_type",
  "SourceNumber": "source_number",
};

export const NUMERIC_FIELDS = [
  "budget", "total", "subtotal", "tax_amount", "amount", "opening_balance", "purchase_price", "year",
  "quantity", "unit_price", "tax_rate", "balance", "purchase_price",
  "useful_life_years", "residual_value", "depreciation_rate", "accumulated_depreciation",
  "location_lat", "location_lng", "allowed_radius_m",
  "_li_quantity", "_li_unit_price", "_li_tax_amount", "_li_total",
];