/**
 * Base44 accepted loose form values (empty strings for dates/numbers, "true"/"false"
 * strings for booleans). Postgres rejects them, so payloads are normalised here before
 * they reach Supabase — page code stays untouched.
 *
 * Column types come from entity-field-types.json, regenerated by
 * `npm run schema:generate` alongside the migration.
 */
import fieldTypes from "./entity-field-types.json";

function isPlainObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function coerceValue(value, colType) {
  if (value === undefined) return undefined;

  if (colType === "text") {
    if (value === null) return null;
    if (typeof value === "string") return value;
    if (isPlainObject(value) || Array.isArray(value)) return JSON.stringify(value);
    return String(value);
  }

  if (typeof value === "string" && value.trim() === "") return null;
  if (value === null) return null;

  switch (colType) {
    case "double precision": {
      if (typeof value === "number") return value;
      const num = Number(value);
      return Number.isNaN(num) ? null : num;
    }
    case "boolean": {
      if (typeof value === "boolean") return value;
      const normalized = String(value).toLowerCase();
      if (["true", "1", "yes"].includes(normalized)) return true;
      if (["false", "0", "no"].includes(normalized)) return false;
      return null;
    }
    case "date":
      // Postgres `date` wants YYYY-MM-DD; trim ISO timestamps down.
      return typeof value === "string" ? value.slice(0, 10) : value;
    case "timestamptz":
      return value instanceof Date ? value.toISOString() : value;
    case "jsonb":
      return value;
    default:
      return value;
  }
}

/**
 * Normalise a write payload for an entity: coerce values to their column types and
 * drop fields that have no column (a stale Base44 export would otherwise fail the
 * whole insert).
 */
export function coerceRow(entityName, row) {
  const columns = fieldTypes[entityName];
  if (!columns || !isPlainObject(row)) return row;

  const out = {};
  const unknown = [];

  for (const [field, value] of Object.entries(row)) {
    const colType = columns[field];
    if (!colType) {
      unknown.push(field);
      continue;
    }
    const coerced = coerceValue(value, colType);
    if (coerced !== undefined) out[field] = coerced;
  }

  if (unknown.length) {
    console.warn(
      `[compat] ${entityName}: ignoring field(s) with no column: ${unknown.join(", ")}. ` +
        `Run "npm run schema:generate" and apply the migration if the schema changed.`
    );
  }

  return out;
}
